//
//  Department.swift
//  Monumental
//
//  Created by Giovanni Gabriel on 28/11/2023.
//

import Foundation

struct Department {
    let code: String
    let name: String

}
// MARK: - Depatement List
struct DepartmentManager {
    static let departments: [Department] = [
        Department(code: "01", name: "Ain"),
        Department(code: "02", name: "Aisne"),
        Department(code: "03", name: "Allier"),
        Department(code: "04", name: "Alpes-de-Haute-Provence"),
        Department(code: "05", name: "Hautes-alpes"),
        Department(code: "06", name: "Alpes-maritimes"),
        Department(code: "07", name: "Ardèche"),
        Department(code: "08", name: "Ardennes"),
        Department(code: "09", name: "Ariège"),
        Department(code: "10", name: "Aube"),
        Department(code: "11", name: "Aude"),
        Department(code: "12", name: "Aveyron"),
        Department(code: "13", name: "Bouches-du-Rhône"),
        Department(code: "14", name: "Calvados"),
        Department(code: "15", name: "Cantal"),
        Department(code: "16", name: "Charente"),
        Department(code: "17", name: "Charente-maritime"),
        Department(code: "18", name: "Cher"),
        Department(code: "19", name: "Corrèze"),
        Department(code: "2A", name: "Corse-du-sud"),
        Department(code: "2B", name: "Haute-Corse"),
        Department(code: "21", name: "Côte-d'Or"),
        Department(code: "22", name: "Côtes-d'Armor"),
        Department(code: "23", name: "Creuse"),
        Department(code: "24", name: "Dordogne"),
        Department(code: "25", name: "Doubs"),
        Department(code: "26", name: "Drôme"),
        Department(code: "27", name: "Eure"),
        Department(code: "28", name: "Eure-et-loire"),
        Department(code: "29", name: "Finistère"),
        Department(code: "30", name: "Gard"),
        Department(code: "31", name: "Haute-garonne"),
        Department(code: "32", name: "Gers"),
        Department(code: "33", name: "Gironde"),
        Department(code: "34", name: "Hérault"),
        Department(code: "35", name: "Ille-et-vilaine"),
        Department(code: "36", name: "Indre"),
        Department(code: "37", name: "Indre-et-loire"),
        Department(code: "38", name: "Isère"),
        Department(code: "39", name: "Jura"),
        Department(code: "40", name: "Landes"),
        Department(code: "41", name: "Loir-et-cher"),
        Department(code: "42", name: "Loire"),
        Department(code: "43", name: "Haute-loire"),
        Department(code: "44", name: "Loire-atlantique"),
        Department(code: "45", name: "Loiret"),
        Department(code: "46", name: "Lot"),
        Department(code: "47", name: "Lot-et-garonne"),
        Department(code: "48", name: "Lozère"),
        Department(code: "49", name: "Maine-et-loire"),
        Department(code: "50", name: "Manche"),
        Department(code: "51", name: "Marne"),
        Department(code: "52", name: "Haute-marne"),
        Department(code: "53", name: "Mayenne"),
        Department(code: "54", name: "Meurthe-et-moselle"),
        Department(code: "55", name: "Meuse"),
        Department(code: "56", name: "Morbihan"),
        Department(code: "57", name: "Moselle"),
        Department(code: "58", name: "Nièvre"),
        Department(code: "59", name: "Nord"),
        Department(code: "60", name: "Oise"),
        Department(code: "61", name: "Orne"),
        Department(code: "62", name: "Pas-de-calais"),
        Department(code: "63", name: "Puy-de-dôme"),
        Department(code: "64", name: "Pyrénées-atlantiques"),
        Department(code: "65", name: "Hautes-Pyrénées"),
        Department(code: "66", name: "Pyrénées-orientales"),
        Department(code: "67", name: "Bas-rhin"),
        Department(code: "68", name: "Haut-rhin"),
        Department(code: "69", name: "Rhône"),
        Department(code: "70", name: "Haute-saône"),
        Department(code: "71", name: "Saône-et-loire"),
        Department(code: "72", name: "Sarthe"),
        Department(code: "73", name: "Savoie"),
        Department(code: "74", name: "Haute-savoie"),
        Department(code: "75", name: "Paris"),
        Department(code: "76", name: "Seine-maritime"),
        Department(code: "77", name: "Seine-et-marne"),
        Department(code: "78", name: "Yvelines"),
        Department(code: "79", name: "Deux-sèvres"),
        Department(code: "80", name: "Somme"),
        Department(code: "81", name: "Tarn"),
        Department(code: "82", name: "Tarn-et-Garonne"),
        Department(code: "83", name: "Var"),
        Department(code: "84", name: "Vaucluse"),
        Department(code: "85", name: "Vendée"),
        Department(code: "86", name: "Vienne"),
        Department(code: "87", name: "Haute-vienne"),
        Department(code: "88", name: "Vosges"),
        Department(code: "89", name: "Yonne"),
        Department(code: "90", name: "Territoire de belfort"),
        Department(code: "91", name: "Essonne"),
        Department(code: "92", name: "Hauts-de-seine"),
        Department(code: "93", name: "Seine-Saint-Denis"),
        Department(code: "94", name: "Val-de-marne"),
        Department(code: "95", name: "Val-d'Oise"),
        Department(code: "971", name: "Guadeloupe"),
        Department(code: "972", name: "Martinique"),
        Department(code: "973", name: "Guyane"),
        Department(code: "974", name: "Réunion"),
        Department(code: "976", name: "Mayotte")
    ]
    static var currentName = "Guadeloupe"
}
